### ISSUE TITLE
Add leader election to allow for replication

### ISSUE THREAD

**Issue by justbert** [StatCan/ingress-istio-controller#22]
In an effort to increase the resiliency of the system, implement leader election functionality so that many replicas may be deployed for redundancy.

https://docs.openshift.com/container-platform/4.5/operators/operator_sdk/osdk-leader-election.html
https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/

**Comment by justbert** [comment]
@zachomedia You mentioned this last night, right? My brain is a bit fuzzy.

**Comment by zachomedia** [comment]
Yup, I did! It would be useful to allow it to recover quickly in the event of a node going offline.

This is how I did it in the sidecar terminator: https://github.com/zachomedia/kubernetes-sidecar-terminator/blob/master/cmd/root.go#L98..L165

**Comment by justbert** [comment]
Completed in https://github.com/StatCan/ingress-istio-controller/pull/27
